package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestProcessRows(t *testing.T) {
	tests := []struct {
		name         string
		inputRows    []CSVRow
		wantOutput   UploadInventoryInput
		wantErrs     []Error
		wantErrCount int // Count of errors, helpful if expecting multiple errors
	}{
		{
			name: "New Contract, LI, Batch (Complete)",
			inputRows: []CSVRow{
				{
					Vendor:                  "MyVendor",
					MaterialCode:            "101642",
					MaterialDesc:            "Example Material",
					ContractNo:              "C123",
					PONumber:                "PO-001",
					POLineItem:              "10",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "10-02-2024",
					BatchNo:                 "1/10",
					BatchDueDate:            "11-06-2025",
					DrumSize:                250,
					TotalNoOfDrums:          3,
					TotalQty:                750,
					AvailableDrumNos:        []int{1},
					AvailableFullDrums:      1,
					FullDrumTotalQuantity:   250,
					BufferDrumNo:            []int{2},
					BufferNoOfDrums:         1,
					BufferQuantity:          250,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{3},
					SampleLength:            []float64{2.5},
					NoOfShortLengthDrums:    1,
					ShortLengthTotalQty:     247.5,
					ApprovedDrumNumbers:     []int{1, 2, 3},
					BatchTestReportDate:     "10-06-2024",
					Remarks:                 "Partial Buffer",
					BatchTestReportFileName: "Test_report_a.pdf",
				},
			},
			wantOutput: UploadInventoryInput{
				Contracts: []Contracts{
					{
						ContractNo: "C123",
						LIs: []LI{
							{
								MaterialCode:    "101642",
								LiCode:          "LI001",
								LiNumber:        "1",
								Description:     "Example Material",
								HosApprovalDate: "10-02-2024",
								Status:          "VENDOR_ACKNOWLEDGED",
								Batches: []Batch{
									{
										BatchNo:        "1/10",
										SubmissionDate: "11-06-2025",
										TotalQuantity:  750,
										Status:         "PARTIAL_BUFFER",
										Remarks:        "Partial Buffer",
										BatchTestApprovals: []BatchTestApproval{
											{
												ApprovalDate: "10-06-2024",
												TestDrumNumbers: []BatchTestDrumNumbers{
													{
														DrumSize: 250,
														DrumNumbers: []DrumDetails{
															{DrumNumber: 3, Quantity: 2.5},
														},
													},
												},
												ApprovalDrumNumbers: []ApprovalDrumNumber{
													{
														DrumSize:    250,
														DrumNumbers: []int{1, 2, 3},
													},
												},
												Status:          "APPROVED",
												ApprovalComment: "Batch Test report uploaded on Go-live phase 1",
											},
										},
										DrumPartitions: []DrumPartition{
											{
												DrumSize:             250,
												Quantity:             750,
												UnapprovedQuantity:   0,
												AvailableQuantity:    250,
												AvailableDrumNumbers: []int{1},
												BufferQuantity:       250,
												BufferDrumNumbers:    []int{2},
												TestQuantity:         2.5,
												TestDrumNumbers: []DrumDetails{
													{DrumNumber: 3, Quantity: 2.5},
												},
												ShortQuantity: 247.5,
												ShortDrumNumbers: []DrumDetails{
													{DrumNumber: 3, Quantity: 247.5},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
			wantErrs:     nil,
			wantErrCount: 0,
		},
		{
			name: "Two Valid Rows, Different Contracts (All Fields)",
			inputRows: []CSVRow{
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "2024-02-12",
					BatchNo:                 "B001",
					BatchDueDate:            "2024-10-10",
					DrumSize:                200,
					TotalNoOfDrums:          5, // Will cause a drum split
					TotalQty:                1000,
					AvailableDrumNos:        []int{101, 102, 103},
					AvailableFullDrums:      3,
					FullDrumTotalQuantity:   600,
					BufferDrumNo:            []int{104},
					BufferNoOfDrums:         1,
					BufferQuantity:          200,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{105},
					SampleLength:            []float64{2.5},
					NoOfShortLengthDrums:    1,
					ShortLengthTotalQty:     197.5,
					ApprovedDrumNumbers:     []int{101, 102, 103, 104, 105},
					BatchTestReportDate:     "2024-05-01",
					Remarks:                 "Some Remarks",
					BatchTestReportFileName: "report_a.pdf",
				},
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "B123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "2024-02-12",
					BatchNo:                 "B001",
					BatchDueDate:            "2024-10-10",
					DrumSize:                200,
					TotalNoOfDrums:          5,
					TotalQty:                1000,
					AvailableDrumNos:        []int{101, 102, 103},
					AvailableFullDrums:      3,
					FullDrumTotalQuantity:   600,
					BufferDrumNo:            []int{104},
					BufferNoOfDrums:         1,
					BufferQuantity:          200,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{105},
					SampleLength:            []float64{2.5},
					NoOfShortLengthDrums:    1,
					ShortLengthTotalQty:     197.5,
					ApprovedDrumNumbers:     []int{101, 102, 103, 104, 105},
					BatchTestReportDate:     "2024-05-01",
					Remarks:                 "Some Remarks",
					BatchTestReportFileName: "report_a.pdf",
				},
			},
			wantOutput: UploadInventoryInput{
				Contracts: []Contracts{
					{ // Contract 1
						ContractNo: "C123",
						LIs: []LI{
							{
								LiCode:          "LI001",
								LiNumber:        "1",
								MaterialCode:    "MAT100",
								Description:     "Material A",
								HosApprovalDate: "2024-02-12",
								Status:          "VENDOR_ACKNOWLEDGED",
								Batches: []Batch{
									{
										BatchNo:        "B001",
										TotalQuantity:  1000,
										SubmissionDate: "2024-10-10",
										Remarks:        "Some Remarks",
										Status:         "PARTIAL_BUFFER", // Update based on your logic
										BatchTestApprovals: []BatchTestApproval{
											{
												ApprovalDate: "2024-05-01",
												TestDrumNumbers: []BatchTestDrumNumbers{
													{
														DrumSize:    200,
														DrumNumbers: []DrumDetails{{DrumNumber: 105, Quantity: 2.5}},
													},
												},
												ApprovalDrumNumbers: []ApprovalDrumNumber{
													{
														DrumSize:    200,
														DrumNumbers: []int{101, 102, 103, 104, 105},
													},
												},
												Status:          "APPROVED",
												ApprovalComment: "Batch Test report uploaded on Go-live phase 1",
											},
										},
										DrumPartitions: []DrumPartition{
											{
												DrumSize:             200,
												Quantity:             1000,
												UnapprovedQuantity:   0,
												AvailableQuantity:    600,
												AvailableDrumNumbers: []int{101, 102, 103},
												BufferQuantity:       200,
												BufferDrumNumbers:    []int{104},
												TestQuantity:         2.5,
												TestDrumNumbers:      []DrumDetails{{DrumNumber: 105, Quantity: 2.5}},
												ShortQuantity:        197.5,
												ShortDrumNumbers:     []DrumDetails{{DrumNumber: 105, Quantity: 197.5}},
											},
										},
									},
								},
							},
						},
					},
					{ // Contract 1
						ContractNo: "B123",
						LIs: []LI{
							{
								LiCode:          "LI001",
								LiNumber:        "1",
								MaterialCode:    "MAT100",
								Description:     "Material A",
								HosApprovalDate: "2024-02-12",
								Status:          "VENDOR_ACKNOWLEDGED",
								Batches: []Batch{
									{
										BatchNo:        "B001",
										TotalQuantity:  1000,
										SubmissionDate: "2024-10-10",
										Remarks:        "Some Remarks",
										Status:         "PARTIAL_BUFFER", // Update based on your logic
										BatchTestApprovals: []BatchTestApproval{
											{
												ApprovalDate: "2024-05-01",
												TestDrumNumbers: []BatchTestDrumNumbers{
													{
														DrumSize:    200,
														DrumNumbers: []DrumDetails{{DrumNumber: 105, Quantity: 2.5}},
													},
												},
												ApprovalDrumNumbers: []ApprovalDrumNumber{
													{
														DrumSize:    200,
														DrumNumbers: []int{101, 102, 103, 104, 105},
													},
												},
												Status:          "APPROVED",
												ApprovalComment: "Batch Test report uploaded on Go-live phase 1",
											},
										},
										DrumPartitions: []DrumPartition{
											{
												DrumSize:             200,
												Quantity:             1000,
												UnapprovedQuantity:   0,
												AvailableQuantity:    600,
												AvailableDrumNumbers: []int{101, 102, 103},
												BufferQuantity:       200,
												BufferDrumNumbers:    []int{104},
												TestQuantity:         2.5,
												TestDrumNumbers:      []DrumDetails{{DrumNumber: 105, Quantity: 2.5}},
												ShortQuantity:        197.5,
												ShortDrumNumbers:     []DrumDetails{{DrumNumber: 105, Quantity: 197.5}},
											},
										},
									},
								},
							},
						},
					},
				},
			},
			wantErrs:     nil,
			wantErrCount: 0,
		},
		{
			name: "Same Contract, Two Different LIs (All Fields)",
			inputRows: []CSVRow{
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "01-01-2024",
					BatchNo:                 "B001",
					BatchDueDate:            "01-01-2025",
					DrumSize:                200,
					TotalNoOfDrums:          5,
					TotalQty:                1000,
					AvailableDrumNos:        []int{101, 102, 103},
					AvailableFullDrums:      3,
					FullDrumTotalQuantity:   600,
					BufferDrumNo:            []int{104},
					BufferNoOfDrums:         1,
					BufferQuantity:          200,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{105},
					SampleLength:            []float64{5.0},
					NoOfShortLengthDrums:    1,
					ShortLengthTotalQty:     195,
					ApprovedDrumNumbers:     []int{101, 102, 103, 104, 105},
					BatchTestReportDate:     "01-02-2024",
					Remarks:                 "Initial LI",
					BatchTestReportFileName: "test_a.pdf",
				},
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT101",
					MaterialDesc:            "Material B",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "2"},
					LIDate:                  "01-01-2024",
					BatchNo:                 "B001",
					BatchDueDate:            "01-01-2025",
					DrumSize:                200,
					TotalNoOfDrums:          5,
					TotalQty:                1000,
					AvailableDrumNos:        []int{101, 102, 103},
					AvailableFullDrums:      3,
					FullDrumTotalQuantity:   600,
					BufferDrumNo:            []int{104},
					BufferNoOfDrums:         1,
					BufferQuantity:          200,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{105},
					SampleLength:            []float64{5.0},
					NoOfShortLengthDrums:    1,
					ShortLengthTotalQty:     195,
					ApprovedDrumNumbers:     []int{101, 102, 103, 104, 105},
					BatchTestReportDate:     "01-02-2024",
					Remarks:                 "Initial LI",
					BatchTestReportFileName: "test_b.pdf",
				},
			},
			wantOutput: UploadInventoryInput{
				Contracts: []Contracts{
					{ // Contract 1
						ContractNo: "C123",
						LIs: []LI{
							{
								LiCode:          "LI001",
								LiNumber:        "1",
								MaterialCode:    "MAT100",
								Description:     "Material A",
								HosApprovalDate: "01-01-2024",
								Status:          "VENDOR_ACKNOWLEDGED",
								Batches: []Batch{
									{
										BatchNo:        "B001",
										TotalQuantity:  1000,
										SubmissionDate: "01-01-2025",
										Remarks:        "Initial LI",
										Status:         "PARTIAL_BUFFER", // Update based on your logic
										BatchTestApprovals: []BatchTestApproval{
											{
												ApprovalDate: "01-02-2024",
												TestDrumNumbers: []BatchTestDrumNumbers{
													{
														DrumSize:    200,
														DrumNumbers: []DrumDetails{{DrumNumber: 105, Quantity: 5}},
													},
												},
												ApprovalDrumNumbers: []ApprovalDrumNumber{
													{
														DrumSize:    200,
														DrumNumbers: []int{101, 102, 103, 104, 105},
													},
												},
												Status:          "APPROVED",
												ApprovalComment: "Batch Test report uploaded on Go-live phase 1",
											},
										},
										DrumPartitions: []DrumPartition{
											{
												DrumSize:             200,
												Quantity:             1000,
												UnapprovedQuantity:   0,
												AvailableQuantity:    600,
												AvailableDrumNumbers: []int{101, 102, 103},
												BufferQuantity:       200,
												BufferDrumNumbers:    []int{104},
												TestQuantity:         5,
												TestDrumNumbers:      []DrumDetails{{DrumNumber: 105, Quantity: 5}},
												ShortQuantity:        195,
												ShortDrumNumbers:     []DrumDetails{{DrumNumber: 105, Quantity: 195}},
											},
										},
									},
								},
							},
							{
								LiCode:          "LI001",
								LiNumber:        "2",
								MaterialCode:    "MAT101",
								Description:     "Material B",
								HosApprovalDate: "01-01-2024",
								Status:          "VENDOR_ACKNOWLEDGED",
								Batches: []Batch{
									{
										BatchNo:        "B001",
										TotalQuantity:  1000,
										SubmissionDate: "01-01-2025",
										Remarks:        "Initial LI",
										Status:         "PARTIAL_BUFFER", // Update based on your logic
										BatchTestApprovals: []BatchTestApproval{
											{
												ApprovalDate: "01-02-2024",
												TestDrumNumbers: []BatchTestDrumNumbers{
													{
														DrumSize:    200,
														DrumNumbers: []DrumDetails{{DrumNumber: 105, Quantity: 5}},
													},
												},
												ApprovalDrumNumbers: []ApprovalDrumNumber{
													{
														DrumSize:    200,
														DrumNumbers: []int{101, 102, 103, 104, 105},
													},
												},
												Status:          "APPROVED",
												ApprovalComment: "Batch Test report uploaded on Go-live phase 1",
											},
										},
										DrumPartitions: []DrumPartition{
											{
												DrumSize:             200,
												Quantity:             1000,
												UnapprovedQuantity:   0,
												AvailableQuantity:    600,
												AvailableDrumNumbers: []int{101, 102, 103},
												BufferQuantity:       200,
												BufferDrumNumbers:    []int{104},
												TestQuantity:         5,
												TestDrumNumbers:      []DrumDetails{{DrumNumber: 105, Quantity: 5}},
												ShortQuantity:        195,
												ShortDrumNumbers:     []DrumDetails{{DrumNumber: 105, Quantity: 195}},
											},
										},
									},
								},
							},
						},
					},
				},
			},
			wantErrs:     nil,
			wantErrCount: 0,
		},
		{
			name: "same batch no., same drum size, same approval date",
			inputRows: []CSVRow{
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "2024-02-12",
					BatchNo:                 "1/2",
					BatchDueDate:            "2024-10-10",
					DrumSize:                200,
					TotalNoOfDrums:          5,
					TotalQty:                1000,
					AvailableDrumNos:        []int{101, 102, 103},
					AvailableFullDrums:      3,
					FullDrumTotalQuantity:   600,
					BufferDrumNo:            []int{104},
					BufferNoOfDrums:         1,
					BufferQuantity:          200,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{105},
					SampleLength:            []float64{2.5},
					NoOfShortLengthDrums:    1,
					ShortLengthTotalQty:     197.5,
					ApprovedDrumNumbers:     []int{101, 102, 103, 104, 105},
					BatchTestReportDate:     "2024-05-01",
					Remarks:                 "Some Remarks",
					BatchTestReportFileName: "report_a.pdf",
				},
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "2024-02-12",
					BatchNo:                 "1/2",
					BatchDueDate:            "2024-10-10",
					DrumSize:                200,
					TotalNoOfDrums:          2,
					TotalQty:                400,
					AvailableDrumNos:        []int{106},
					AvailableFullDrums:      1,
					FullDrumTotalQuantity:   200,
					BufferDrumNo:            []int{},
					BufferNoOfDrums:         0,
					BufferQuantity:          0,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{107},
					SampleLength:            []float64{2.5},
					NoOfShortLengthDrums:    1,
					ShortLengthTotalQty:     197.5,
					ApprovedDrumNumbers:     []int{106, 107},
					BatchTestReportDate:     "2024-05-01",
					Remarks:                 "Some Remarks",
					BatchTestReportFileName: "report_a.pdf",
				},
			},
			wantOutput: UploadInventoryInput{
				Contracts: []Contracts{
					{ // Contract 1
						ContractNo: "C123",
						LIs: []LI{
							{
								LiCode:          "LI001",
								LiNumber:        "1",
								MaterialCode:    "MAT100",
								Description:     "Material A",
								HosApprovalDate: "2024-02-12",
								Status:          "VENDOR_ACKNOWLEDGED",
								Batches: []Batch{
									{
										BatchNo:        "1/2",
										TotalQuantity:  1400,
										SubmissionDate: "2024-10-10",
										Remarks:        "Some Remarks",
										Status:         "PARTIAL_BUFFER", // Update based on your logic
										BatchTestApprovals: []BatchTestApproval{
											{
												ApprovalDate: "2024-05-01",
												TestDrumNumbers: []BatchTestDrumNumbers{
													{
														DrumSize:    200,
														DrumNumbers: []DrumDetails{{DrumNumber: 105, Quantity: 2.5}, {DrumNumber: 107, Quantity: 2.5}},
													},
												},
												ApprovalDrumNumbers: []ApprovalDrumNumber{
													{
														DrumSize:    200,
														DrumNumbers: []int{101, 102, 103, 104, 105, 106, 107},
													},
												},
												Status:          "APPROVED",
												ApprovalComment: "Batch Test report uploaded on Go-live phase 1",
											},
										},
										DrumPartitions: []DrumPartition{
											{
												DrumSize:             200,
												Quantity:             1400,
												UnapprovedQuantity:   0,
												AvailableQuantity:    800,
												AvailableDrumNumbers: []int{101, 102, 103, 106},
												BufferQuantity:       200,
												BufferDrumNumbers:    []int{104},
												TestQuantity:         5,
												TestDrumNumbers:      []DrumDetails{{DrumNumber: 105, Quantity: 2.5}, {DrumNumber: 107, Quantity: 2.5}},
												ShortQuantity:        395,
												ShortDrumNumbers:     []DrumDetails{{DrumNumber: 105, Quantity: 197.5}, {DrumNumber: 107, Quantity: 197.5}},
											},
										},
									},
								},
							},
						},
					},
				},
			},
			wantErrs:     nil,
			wantErrCount: 0,
		},
		{
			name: "same batch no., same drum size, different approval date",
			inputRows: []CSVRow{
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "2024-02-12",
					BatchNo:                 "1/2",
					BatchDueDate:            "2024-10-10",
					DrumSize:                200,
					TotalNoOfDrums:          5,
					TotalQty:                1000,
					AvailableDrumNos:        []int{101, 102, 103},
					AvailableFullDrums:      3,
					FullDrumTotalQuantity:   600,
					BufferDrumNo:            []int{104},
					BufferNoOfDrums:         1,
					BufferQuantity:          200,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{105},
					SampleLength:            []float64{2.5},
					NoOfShortLengthDrums:    1,
					ShortLengthTotalQty:     197.5,
					ApprovedDrumNumbers:     []int{101, 102, 103, 104, 105},
					BatchTestReportDate:     "2024-05-01",
					Remarks:                 "Some Remarks",
					BatchTestReportFileName: "report_a.pdf",
				},
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "2024-02-12",
					BatchNo:                 "1/2",
					BatchDueDate:            "2024-10-10",
					DrumSize:                200,
					TotalNoOfDrums:          2,
					TotalQty:                400,
					AvailableDrumNos:        []int{106},
					AvailableFullDrums:      1,
					FullDrumTotalQuantity:   200,
					BufferDrumNo:            []int{},
					BufferNoOfDrums:         0,
					BufferQuantity:          0,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{107},
					SampleLength:            []float64{2.5},
					NoOfShortLengthDrums:    1,
					ShortLengthTotalQty:     197.5,
					ApprovedDrumNumbers:     []int{106, 107},
					BatchTestReportDate:     "2024-05-02",
					Remarks:                 "Some Remarks",
					BatchTestReportFileName: "report_a.pdf",
				},
			},
			wantOutput: UploadInventoryInput{
				Contracts: []Contracts{
					{ // Contract 1
						ContractNo: "C123",
						LIs: []LI{
							{
								LiCode:          "LI001",
								LiNumber:        "1",
								MaterialCode:    "MAT100",
								Description:     "Material A",
								HosApprovalDate: "2024-02-12",
								Status:          "VENDOR_ACKNOWLEDGED",
								Batches: []Batch{
									{
										BatchNo:        "1/2",
										TotalQuantity:  1400,
										SubmissionDate: "2024-10-10",
										Remarks:        "Some Remarks",
										Status:         "PARTIAL_BUFFER", // Update based on your logic
										BatchTestApprovals: []BatchTestApproval{
											{
												ApprovalDate: "2024-05-01",
												TestDrumNumbers: []BatchTestDrumNumbers{
													{
														DrumSize:    200,
														DrumNumbers: []DrumDetails{{DrumNumber: 105, Quantity: 2.5}},
													},
												},
												ApprovalDrumNumbers: []ApprovalDrumNumber{
													{
														DrumSize:    200,
														DrumNumbers: []int{101, 102, 103, 104, 105},
													},
												},
												Status:          "APPROVED",
												ApprovalComment: "Batch Test report uploaded on Go-live phase 1",
											},
											{
												ApprovalDate: "2024-05-02",
												TestDrumNumbers: []BatchTestDrumNumbers{
													{
														DrumSize:    200,
														DrumNumbers: []DrumDetails{{DrumNumber: 107, Quantity: 2.5}},
													},
												},
												ApprovalDrumNumbers: []ApprovalDrumNumber{
													{
														DrumSize:    200,
														DrumNumbers: []int{106, 107},
													},
												},
												Status:          "APPROVED",
												ApprovalComment: "Batch Test report uploaded on Go-live phase 1",
											},
										},
										DrumPartitions: []DrumPartition{
											{
												DrumSize:             200,
												Quantity:             1400,
												UnapprovedQuantity:   0,
												AvailableQuantity:    800,
												AvailableDrumNumbers: []int{101, 102, 103, 106},
												BufferQuantity:       200,
												BufferDrumNumbers:    []int{104},
												TestQuantity:         5,
												TestDrumNumbers:      []DrumDetails{{DrumNumber: 105, Quantity: 2.5}, {DrumNumber: 107, Quantity: 2.5}},
												ShortQuantity:        395,
												ShortDrumNumbers:     []DrumDetails{{DrumNumber: 105, Quantity: 197.5}, {DrumNumber: 107, Quantity: 197.5}},
											},
										},
									},
								},
							},
						},
					},
				},
			},
			wantErrs:     nil,
			wantErrCount: 0,
		},
		{
			name: "same batch no., same drum size, no approval date",
			inputRows: []CSVRow{
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "2024-02-12",
					BatchNo:                 "1/2",
					BatchDueDate:            "2024-10-10",
					DrumSize:                200,
					TotalNoOfDrums:          5,
					TotalQty:                1000,
					AvailableDrumNos:        []int{101, 102, 103},
					AvailableFullDrums:      3,
					FullDrumTotalQuantity:   600,
					BufferDrumNo:            []int{104},
					BufferNoOfDrums:         1,
					BufferQuantity:          200,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{105},
					SampleLength:            []float64{2.5},
					NoOfShortLengthDrums:    1,
					ShortLengthTotalQty:     197.5,
					ApprovedDrumNumbers:     []int{101, 102, 103, 104, 105},
					BatchTestReportDate:     "2024-05-01",
					Remarks:                 "Some Remarks",
					BatchTestReportFileName: "report_a.pdf",
				},
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "2024-02-12",
					BatchNo:                 "1/2",
					BatchDueDate:            "2024-10-10",
					DrumSize:                200,
					TotalNoOfDrums:          2,
					TotalQty:                400,
					AvailableDrumNos:        []int{},
					AvailableFullDrums:      0,
					FullDrumTotalQuantity:   0,
					BufferDrumNo:            []int{},
					BufferNoOfDrums:         0,
					BufferQuantity:          0,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{},
					SampleLength:            []float64{},
					NoOfShortLengthDrums:    0,
					ShortLengthTotalQty:     0,
					ApprovedDrumNumbers:     []int{},
					BatchTestReportDate:     "",
					Remarks:                 "Some Remarks",
					BatchTestReportFileName: "",
				},
			},
			wantOutput: UploadInventoryInput{
				Contracts: []Contracts{
					{ // Contract 1
						ContractNo: "C123",
						LIs: []LI{
							{
								LiCode:          "LI001",
								LiNumber:        "1",
								MaterialCode:    "MAT100",
								Description:     "Material A",
								HosApprovalDate: "2024-02-12",
								Status:          "VENDOR_ACKNOWLEDGED",
								Batches: []Batch{
									{
										BatchNo:        "1/2",
										TotalQuantity:  1400,
										SubmissionDate: "2024-10-10",
										Remarks:        "Some Remarks",
										Status:         "PARTIAL_BUFFER", // Update based on your logic
										BatchTestApprovals: []BatchTestApproval{
											{
												ApprovalDate: "2024-05-01",
												TestDrumNumbers: []BatchTestDrumNumbers{
													{
														DrumSize:    200,
														DrumNumbers: []DrumDetails{{DrumNumber: 105, Quantity: 2.5}},
													},
												},
												ApprovalDrumNumbers: []ApprovalDrumNumber{
													{
														DrumSize:    200,
														DrumNumbers: []int{101, 102, 103, 104, 105},
													},
												},
												Status:          "APPROVED",
												ApprovalComment: "Batch Test report uploaded on Go-live phase 1",
											},
										},
										DrumPartitions: []DrumPartition{
											{
												DrumSize:             200,
												Quantity:             1400,
												UnapprovedQuantity:   400,
												AvailableQuantity:    600,
												AvailableDrumNumbers: []int{101, 102, 103},
												BufferQuantity:       200,
												BufferDrumNumbers:    []int{104},
												TestQuantity:         2.5,
												TestDrumNumbers:      []DrumDetails{{DrumNumber: 105, Quantity: 2.5}},
												ShortQuantity:        197.5,
												ShortDrumNumbers:     []DrumDetails{{DrumNumber: 105, Quantity: 197.5}},
											},
										},
									},
								},
							},
						},
					},
				},
			},
			wantErrs:     nil,
			wantErrCount: 0,
		},
		{
			name: "same batch no., different drum size, same approval date",
			inputRows: []CSVRow{
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "2024-02-12",
					BatchNo:                 "1/2",
					BatchDueDate:            "2024-10-10",
					DrumSize:                200,
					TotalNoOfDrums:          5,
					TotalQty:                1000,
					AvailableDrumNos:        []int{1, 2, 3},
					AvailableFullDrums:      3,
					FullDrumTotalQuantity:   600,
					BufferDrumNo:            []int{4},
					BufferNoOfDrums:         1,
					BufferQuantity:          200,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{5},
					SampleLength:            []float64{2.5},
					NoOfShortLengthDrums:    1,
					ShortLengthTotalQty:     197.5,
					ApprovedDrumNumbers:     []int{1, 2, 3, 4, 5},
					BatchTestReportDate:     "2024-05-01",
					Remarks:                 "Some Remarks",
					BatchTestReportFileName: "report_a.pdf",
				},
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "2024-02-12",
					BatchNo:                 "1/2",
					BatchDueDate:            "2024-10-10",
					DrumSize:                300,
					TotalNoOfDrums:          2,
					TotalQty:                600,
					AvailableDrumNos:        []int{6},
					AvailableFullDrums:      1,
					FullDrumTotalQuantity:   300,
					BufferDrumNo:            []int{},
					BufferNoOfDrums:         0,
					BufferQuantity:          0,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{7},
					SampleLength:            []float64{2.5},
					NoOfShortLengthDrums:    1,
					ShortLengthTotalQty:     297.5,
					ApprovedDrumNumbers:     []int{6, 7},
					BatchTestReportDate:     "2024-05-01",
					Remarks:                 "Some Remarks",
					BatchTestReportFileName: "report_a.pdf",
				},
			},
			wantOutput: UploadInventoryInput{
				Contracts: []Contracts{
					{ // Contract 1
						ContractNo: "C123",
						LIs: []LI{
							{
								LiCode:          "LI001",
								LiNumber:        "1",
								MaterialCode:    "MAT100",
								Description:     "Material A",
								HosApprovalDate: "2024-02-12",
								Status:          "VENDOR_ACKNOWLEDGED",
								Batches: []Batch{
									{
										BatchNo:        "1/2",
										TotalQuantity:  1600,
										SubmissionDate: "2024-10-10",
										Remarks:        "Some Remarks",
										Status:         "PARTIAL_BUFFER",
										BatchTestApprovals: []BatchTestApproval{
											{
												ApprovalDate: "2024-05-01",
												TestDrumNumbers: []BatchTestDrumNumbers{
													{
														DrumSize:    200,
														DrumNumbers: []DrumDetails{{DrumNumber: 5, Quantity: 2.5}},
													},
													{
														DrumSize:    300,
														DrumNumbers: []DrumDetails{{DrumNumber: 7, Quantity: 2.5}},
													},
												},
												ApprovalDrumNumbers: []ApprovalDrumNumber{
													{
														DrumSize:    200,
														DrumNumbers: []int{1, 2, 3, 4, 5},
													},
													{
														DrumSize:    300,
														DrumNumbers: []int{6, 7},
													},
												},
												Status:          "APPROVED",
												ApprovalComment: "Batch Test report uploaded on Go-live phase 1",
											},
										},
										DrumPartitions: []DrumPartition{
											{
												DrumSize:             200,
												Quantity:             1000,
												UnapprovedQuantity:   0,
												AvailableQuantity:    600,
												AvailableDrumNumbers: []int{1, 2, 3},
												BufferQuantity:       200,
												BufferDrumNumbers:    []int{4},
												TestQuantity:         2.5,
												TestDrumNumbers:      []DrumDetails{{DrumNumber: 5, Quantity: 2.5}},
												ShortQuantity:        197.5,
												ShortDrumNumbers:     []DrumDetails{{DrumNumber: 5, Quantity: 197.5}},
											},
											{
												DrumSize:             300,
												Quantity:             600,
												UnapprovedQuantity:   0,
												AvailableQuantity:    300,
												AvailableDrumNumbers: []int{6},
												BufferQuantity:       0,
												BufferDrumNumbers:    []int{},
												TestQuantity:         2.5,
												TestDrumNumbers:      []DrumDetails{{DrumNumber: 7, Quantity: 2.5}},
												ShortQuantity:        297.5,
												ShortDrumNumbers:     []DrumDetails{{DrumNumber: 7, Quantity: 297.5}},
											},
										},
									},
								},
							},
						},
					},
				},
			},
			wantErrs:     nil,
			wantErrCount: 0,
		},
		{
			name: "same batch no., different drum size, different approval date",
			inputRows: []CSVRow{
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "2024-02-12",
					BatchNo:                 "1/2",
					BatchDueDate:            "2024-10-10",
					DrumSize:                200,
					TotalNoOfDrums:          5,
					TotalQty:                1000,
					AvailableDrumNos:        []int{1, 2, 3},
					AvailableFullDrums:      3,
					FullDrumTotalQuantity:   600,
					BufferDrumNo:            []int{4},
					BufferNoOfDrums:         1,
					BufferQuantity:          200,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{5},
					SampleLength:            []float64{2.5},
					NoOfShortLengthDrums:    1,
					ShortLengthTotalQty:     197.5,
					ApprovedDrumNumbers:     []int{1, 2, 3, 4, 5},
					BatchTestReportDate:     "2024-05-01",
					Remarks:                 "Some Remarks",
					BatchTestReportFileName: "report_a.pdf",
				},
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "2024-02-12",
					BatchNo:                 "1/2",
					BatchDueDate:            "2024-10-10",
					DrumSize:                300,
					TotalNoOfDrums:          2,
					TotalQty:                600,
					AvailableDrumNos:        []int{6},
					AvailableFullDrums:      1,
					FullDrumTotalQuantity:   300,
					BufferDrumNo:            []int{},
					BufferNoOfDrums:         0,
					BufferQuantity:          0,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{7},
					SampleLength:            []float64{2.5},
					NoOfShortLengthDrums:    1,
					ShortLengthTotalQty:     297.5,
					ApprovedDrumNumbers:     []int{6, 7},
					BatchTestReportDate:     "2024-05-02",
					Remarks:                 "Some Remarks",
					BatchTestReportFileName: "report_b.pdf",
				},
			},
			wantOutput: UploadInventoryInput{
				Contracts: []Contracts{
					{ // Contract 1
						ContractNo: "C123",
						LIs: []LI{
							{
								LiCode:          "LI001",
								LiNumber:        "1",
								MaterialCode:    "MAT100",
								Description:     "Material A",
								HosApprovalDate: "2024-02-12",
								Status:          "VENDOR_ACKNOWLEDGED",
								Batches: []Batch{
									{
										BatchNo:        "1/2",
										TotalQuantity:  1600,
										SubmissionDate: "2024-10-10",
										Remarks:        "Some Remarks",
										Status:         "PARTIAL_BUFFER",
										BatchTestApprovals: []BatchTestApproval{
											{
												ApprovalDate: "2024-05-01",
												TestDrumNumbers: []BatchTestDrumNumbers{
													{
														DrumSize:    200,
														DrumNumbers: []DrumDetails{{DrumNumber: 5, Quantity: 2.5}},
													},
												},
												ApprovalDrumNumbers: []ApprovalDrumNumber{
													{
														DrumSize:    200,
														DrumNumbers: []int{1, 2, 3, 4, 5},
													},
												},
												Status:          "APPROVED",
												ApprovalComment: "Batch Test report uploaded on Go-live phase 1",
											},
											{
												ApprovalDate: "2024-05-02",
												TestDrumNumbers: []BatchTestDrumNumbers{
													{
														DrumSize:    300,
														DrumNumbers: []DrumDetails{{DrumNumber: 7, Quantity: 2.5}},
													},
												},
												ApprovalDrumNumbers: []ApprovalDrumNumber{
													{
														DrumSize:    300,
														DrumNumbers: []int{6, 7},
													},
												},
												Status:          "APPROVED",
												ApprovalComment: "Batch Test report uploaded on Go-live phase 1",
											},
										},
										DrumPartitions: []DrumPartition{
											{
												DrumSize:             200,
												Quantity:             1000,
												UnapprovedQuantity:   0,
												AvailableQuantity:    600,
												AvailableDrumNumbers: []int{1, 2, 3},
												BufferQuantity:       200,
												BufferDrumNumbers:    []int{4},
												TestQuantity:         2.5,
												TestDrumNumbers:      []DrumDetails{{DrumNumber: 5, Quantity: 2.5}},
												ShortQuantity:        197.5,
												ShortDrumNumbers:     []DrumDetails{{DrumNumber: 5, Quantity: 197.5}},
											},
											{
												DrumSize:             300,
												Quantity:             600,
												UnapprovedQuantity:   0,
												AvailableQuantity:    300,
												AvailableDrumNumbers: []int{6},
												BufferQuantity:       0,
												BufferDrumNumbers:    []int{},
												TestQuantity:         2.5,
												TestDrumNumbers:      []DrumDetails{{DrumNumber: 7, Quantity: 2.5}},
												ShortQuantity:        297.5,
												ShortDrumNumbers:     []DrumDetails{{DrumNumber: 7, Quantity: 297.5}},
											},
										},
									},
								},
							},
						},
					},
				},
			},
			wantErrs:     nil,
			wantErrCount: 0,
		},
		{
			name: "same batch no., different drum size, no approval date",
			inputRows: []CSVRow{
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "2024-02-12",
					BatchNo:                 "1/2",
					BatchDueDate:            "2024-10-10",
					DrumSize:                200,
					TotalNoOfDrums:          5,
					TotalQty:                1000,
					AvailableDrumNos:        []int{1, 2, 3},
					AvailableFullDrums:      3,
					FullDrumTotalQuantity:   600,
					BufferDrumNo:            []int{4},
					BufferNoOfDrums:         1,
					BufferQuantity:          200,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{5},
					SampleLength:            []float64{2.5},
					NoOfShortLengthDrums:    1,
					ShortLengthTotalQty:     197.5,
					ApprovedDrumNumbers:     []int{1, 2, 3, 4, 5},
					BatchTestReportDate:     "2024-05-01",
					Remarks:                 "Some Remarks",
					BatchTestReportFileName: "report_a.pdf",
				},
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "2024-02-12",
					BatchNo:                 "1/2",
					BatchDueDate:            "2024-10-10",
					DrumSize:                300,
					TotalNoOfDrums:          2,
					TotalQty:                600,
					AvailableDrumNos:        []int{},
					AvailableFullDrums:      0,
					FullDrumTotalQuantity:   0,
					BufferDrumNo:            []int{},
					BufferNoOfDrums:         0,
					BufferQuantity:          0,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{},
					SampleLength:            []float64{},
					NoOfShortLengthDrums:    0,
					ShortLengthTotalQty:     0,
					ApprovedDrumNumbers:     []int{},
					BatchTestReportDate:     "",
					Remarks:                 "Some Remarks",
					BatchTestReportFileName: "",
				},
			},
			wantOutput: UploadInventoryInput{
				Contracts: []Contracts{
					{ // Contract 1
						ContractNo: "C123",
						LIs: []LI{
							{
								LiCode:          "LI001",
								LiNumber:        "1",
								MaterialCode:    "MAT100",
								Description:     "Material A",
								HosApprovalDate: "2024-02-12",
								Status:          "VENDOR_ACKNOWLEDGED",
								Batches: []Batch{
									{
										BatchNo:        "1/2",
										TotalQuantity:  1600,
										SubmissionDate: "2024-10-10",
										Remarks:        "Some Remarks",
										Status:         "PARTIAL_BUFFER",
										BatchTestApprovals: []BatchTestApproval{
											{
												ApprovalDate: "2024-05-01",
												TestDrumNumbers: []BatchTestDrumNumbers{
													{
														DrumSize:    200,
														DrumNumbers: []DrumDetails{{DrumNumber: 5, Quantity: 2.5}},
													},
												},
												ApprovalDrumNumbers: []ApprovalDrumNumber{
													{
														DrumSize:    200,
														DrumNumbers: []int{1, 2, 3, 4, 5},
													},
												},
												Status:          "APPROVED",
												ApprovalComment: "Batch Test report uploaded on Go-live phase 1",
											},
										},
										DrumPartitions: []DrumPartition{
											{
												DrumSize:             200,
												Quantity:             1000,
												UnapprovedQuantity:   0,
												AvailableQuantity:    600,
												AvailableDrumNumbers: []int{1, 2, 3},
												BufferQuantity:       200,
												BufferDrumNumbers:    []int{4},
												TestQuantity:         2.5,
												TestDrumNumbers:      []DrumDetails{{DrumNumber: 5, Quantity: 2.5}},
												ShortQuantity:        197.5,
												ShortDrumNumbers:     []DrumDetails{{DrumNumber: 5, Quantity: 197.5}},
											},
											{
												DrumSize:             300,
												Quantity:             600,
												UnapprovedQuantity:   600,
												AvailableQuantity:    0,
												AvailableDrumNumbers: []int{},
												BufferQuantity:       0,
												BufferDrumNumbers:    []int{},
												TestQuantity:         0,
												TestDrumNumbers:      []DrumDetails{},
												ShortQuantity:        0,
												ShortDrumNumbers:     []DrumDetails{},
											},
										},
									},
								},
							},
						},
					},
				},
			},
			wantErrs:     nil,
			wantErrCount: 0,
		},
		{
			name: "different batch no.",
			inputRows: []CSVRow{
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "2024-02-12",
					BatchNo:                 "1/2",
					BatchDueDate:            "2024-10-10",
					DrumSize:                200,
					TotalNoOfDrums:          5,
					TotalQty:                1000,
					AvailableDrumNos:        []int{101, 102, 103},
					AvailableFullDrums:      3,
					FullDrumTotalQuantity:   600,
					BufferDrumNo:            []int{104},
					BufferNoOfDrums:         1,
					BufferQuantity:          200,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{105},
					SampleLength:            []float64{2.5},
					NoOfShortLengthDrums:    1,
					ShortLengthTotalQty:     197.5,
					ApprovedDrumNumbers:     []int{101, 102, 103, 104, 105},
					BatchTestReportDate:     "2024-05-01",
					Remarks:                 "Some Remarks",
					BatchTestReportFileName: "report_a.pdf",
				},
				{
					Vendor:                  "Supplier A",
					MaterialCode:            "MAT100",
					MaterialDesc:            "Material A",
					ContractNo:              "C123",
					PONumber:                "PO-100",
					POLineItem:              "1",
					LIName:                  LIName{LICode: "LI001", LINumber: "1"},
					LIDate:                  "2024-02-12",
					BatchNo:                 "2/2",
					BatchDueDate:            "2024-12-10",
					DrumSize:                200,
					TotalNoOfDrums:          2,
					TotalQty:                400,
					AvailableDrumNos:        []int{},
					AvailableFullDrums:      0,
					FullDrumTotalQuantity:   0,
					BufferDrumNo:            []int{},
					BufferNoOfDrums:         0,
					BufferQuantity:          0,
					SampleDrum:              "Yes",
					SampleDrumNo:            []int{},
					SampleLength:            []float64{},
					NoOfShortLengthDrums:    0,
					ShortLengthTotalQty:     0,
					ApprovedDrumNumbers:     []int{},
					BatchTestReportDate:     "",
					Remarks:                 "Some Remarks",
					BatchTestReportFileName: "",
				},
			},
			wantOutput: UploadInventoryInput{
				Contracts: []Contracts{
					{ // Contract 1
						ContractNo: "C123",
						LIs: []LI{
							{
								LiCode:          "LI001",
								LiNumber:        "1",
								MaterialCode:    "MAT100",
								Description:     "Material A",
								HosApprovalDate: "2024-02-12",
								Status:          "VENDOR_ACKNOWLEDGED",
								Batches: []Batch{
									{
										BatchNo:        "1/2",
										TotalQuantity:  1000,
										SubmissionDate: "2024-10-10",
										Remarks:        "Some Remarks",
										Status:         "PARTIAL_BUFFER",
										BatchTestApprovals: []BatchTestApproval{
											{
												ApprovalDate: "2024-05-01",
												TestDrumNumbers: []BatchTestDrumNumbers{
													{
														DrumSize:    200,
														DrumNumbers: []DrumDetails{{DrumNumber: 105, Quantity: 2.5}},
													},
												},
												ApprovalDrumNumbers: []ApprovalDrumNumber{
													{
														DrumSize:    200,
														DrumNumbers: []int{101, 102, 103, 104, 105},
													},
												},
												Status:          "APPROVED",
												ApprovalComment: "Batch Test report uploaded on Go-live phase 1",
											},
										},
										DrumPartitions: []DrumPartition{
											{
												DrumSize:             200,
												Quantity:             1000,
												UnapprovedQuantity:   0,
												AvailableQuantity:    600,
												AvailableDrumNumbers: []int{101, 102, 103},
												BufferQuantity:       200,
												BufferDrumNumbers:    []int{104},
												TestQuantity:         2.5,
												TestDrumNumbers:      []DrumDetails{{DrumNumber: 105, Quantity: 2.5}},
												ShortQuantity:        197.5,
												ShortDrumNumbers:     []DrumDetails{{DrumNumber: 105, Quantity: 197.5}},
											},
										},
									},
									{
										BatchNo:            "2/2",
										TotalQuantity:      400,
										SubmissionDate:     "2024-12-10",
										Remarks:            "Some Remarks",
										Status:             "DOCS_PENDING_UPLOAD",
										BatchTestApprovals: []BatchTestApproval{},
										DrumPartitions: []DrumPartition{
											{
												DrumSize:             200,
												Quantity:             400,
												UnapprovedQuantity:   400,
												AvailableQuantity:    0,
												AvailableDrumNumbers: []int{},
												BufferQuantity:       0,
												BufferDrumNumbers:    []int{},
												TestQuantity:         0,
												TestDrumNumbers:      []DrumDetails{},
												ShortQuantity:        0,
												ShortDrumNumbers:     []DrumDetails{},
											},
										},
									},
								},
							},
						},
					},
				},
			},
			wantErrs:     nil,
			wantErrCount: 0,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gotOutput, gotErrs := processRows(tt.inputRows)

			// Assert on the returned output
			assert.Equal(t, tt.wantOutput, gotOutput)

			// Assert on the returned errors
			assert.Equal(t, tt.wantErrCount, len(gotErrs)) // Check the number of errors

			// Optionally, assert specific error messages
			if len(gotErrs) > 0 {
				for i, err := range gotErrs {
					assert.Equal(t, tt.wantErrs[i].Err.Error(), err.Err.Error(), "Error messages should match")
				}
			}
		})
	}
}
